# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TravelBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelBook
  pod 'Firebase/Auth', '~> 6.11.0'
  pod 'Firebase/Core', '~> 6.11.0'
  pod 'Firebase/Firestore', '~> 6.11.0'
  pod 'Firebase/Storage', '~> 6.11.0'
  pod 'FirebaseUI/Google'

end
